# Copyleaks

- Manual input on free account
- Get output as a percentage of text that may be AI-generated

In [1]:
import pandas as pd

In [9]:
df = pd.read_csv('../datasets.csv')

In [10]:
df.shape

(180, 6)

In [11]:
df['copyleaks_AI'] = 100
df['copyleaks_humanized'] = 0
df.head(6)

,topic,length,AI_model,humanizer,AI_essay,humanized_essay,copyleaks_AI,copyleaks_humanized
0,1,1,gemini2.5pro,AIHumanizer,The integration of social media into the lives...,The way social media has woven itself into the...,100,0
1,1,1,gemini2.5pro,Grammarly,The integration of social media into the lives...,Social media has become a big part of young pe...,100,0
2,1,1,gemini2.5pro,HumanizeAI,The integration of social media into the lives...,The penetration of social media into the lives...,100,0
3,1,1,gemini2.5pro,Quillbot,The integration of social media into the lives...,Social media's introduction into young people'...,100,0
4,1,1,gemini2.5pro,UndetectableAI,The integration of social media into the lives...,Young people face a harmful environment throug...,100,0
5,1,1,gemini2.5pro,writehuman.ai,The integration of social media into the lives...,There is an important and critical psychologic...,100,0

In [12]:
df.sort_values(by='humanizer', inplace=True)
df.head(6)

,topic,length,AI_model,humanizer,AI_essay,humanized_essay,copyleaks_AI,copyleaks_humanized
0,1,1,gemini2.5pro,AIHumanizer,The integration of social media into the lives...,The way social media has woven itself into the...,100,0
30,1,3,gpt4.0,AIHumanizer,"In recent years, social media has revolutioniz...","Over the past few years, social media has comp...",100,0
120,4,2,gemini2.5pro,AIHumanizer,Artificial intelligence is rapidly evolving fr...,Artificial intelligence is moving fast from ju...,100,0
156,5,2,gemini2.5pro,AIHumanizer,The landscape of childhood is often painted wi...,Childhood memories are often painted with the ...,100,0
138,4,3,gpt4.0,AIHumanizer,As artificial intelligence (AI) continues to e...,As artificial intelligence (AI) continues to e...,100,0
66,2,3,gpt4.0,AIHumanizer,Fixing a broken fan may seem like a daunting t...,Tackling the task of fixing a broken fan might...,100,0