# Detectability score

### Combine all score from Copyleaks, Sapling, Zerogpt.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../datasets.csv')
df.head()

,topic,length,AI_model,humanizer,AI_essay,humanized_essay
0,1,1,gemini2.5pro,AIHumanizer,The integration of social media into the lives...,The way social media has woven itself into the...
1,1,1,gemini2.5pro,Grammarly,The integration of social media into the lives...,Social media has become a big part of young pe...
2,1,1,gemini2.5pro,HumanizeAI,The integration of social media into the lives...,The penetration of social media into the lives...
3,1,1,gemini2.5pro,Quillbot,The integration of social media into the lives...,Social media's introduction into young people'...
4,1,1,gemini2.5pro,UndetectableAI,The integration of social media into the lives...,Young people face a harmful environment throug...

In [4]:
df.shape

(180, 6)

# Copyleaks
- use the first number, i.e. AI Content Found (Percentage of text that may be AI-generated)
- the second number of AI phrases detected.

In [5]:
df_copyleaks = df.copy()
df_copyleaks['AI_detectability'] = 100
df_copyleaks['humanized_detectability'] = 0
df_copyleaks.head(6)

,topic,length,AI_model,humanizer,AI_essay,humanized_essay,AI_detectability,humanized_detectability
0,1,1,gemini2.5pro,AIHumanizer,The integration of social media into the lives...,The way social media has woven itself into the...,100,0
1,1,1,gemini2.5pro,Grammarly,The integration of social media into the lives...,Social media has become a big part of young pe...,100,0
2,1,1,gemini2.5pro,HumanizeAI,The integration of social media into the lives...,The penetration of social media into the lives...,100,0
3,1,1,gemini2.5pro,Quillbot,The integration of social media into the lives...,Social media's introduction into young people'...,100,0
4,1,1,gemini2.5pro,UndetectableAI,The integration of social media into the lives...,Young people face a harmful environment throug...,100,0
5,1,1,gemini2.5pro,writehuman.ai,The integration of social media into the lives...,There is an important and critical psychologic...,100,0

In [8]:
df_copyleaks.sort_values(by=['humanizer','topic','length'], inplace=True, ignore_index=True)
df_copyleaks.head(6)

,topic,length,AI_model,humanizer,AI_essay,humanized_essay,AI_detectability,humanized_detectability
0,1,1,gemini2.5pro,AIHumanizer,The integration of social media into the lives...,The way social media has woven itself into the...,100,0
1,1,1,gpt4.0,AIHumanizer,Social media has undeniably transformed the wa...,Social media has really changed how young peop...,100,0
2,1,2,gemini2.5pro,AIHumanizer,The pervasive integration of social media into...,The way social media has woven itself into the...,100,0
3,1,2,gpt4.0,AIHumanizer,"In the digital age, social media has become an...","In today’s digital world, social media has rea...",100,0
4,1,3,gpt4.0,AIHumanizer,"In recent years, social media has revolutioniz...","Over the past few years, social media has comp...",100,0
5,1,3,gemini2.5pro,AIHumanizer,The integration of social media into the daily...,Social media has become such a regular part of...,100,0

In [9]:
#AIHumanizer
#set first 30 rows of 'humanized_detectability' to 100
df_copyleaks.loc[0:29, 'humanized_detectability'] = 100

In [10]:
#Grammarly
#set rows 30-59 of 'humanized_detectability' to 100
df_copyleaks.loc[30:59, 'humanized_detectability'] = 100

In [13]:
#HumanizeAI
HumanizeAI = [100, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64.4, 100, 100, 100, 100, 73.1, 100, 100, 100, 0, 100, 100, 45.2]
#set rows 60-89 of 'humanized_detectability' to HumanizeAI list
df_copyleaks.loc[60:89, 'humanized_detectability'] = HumanizeAI

In [15]:
#Quillbot
Quillbot = [100, 100, 80.3, 100, 100, 100, 100, 100, 0, 100, 0, 100 ,100 ,100 ,100 ,100 ,100 ,100, 0, 100,100, 100, 100, 100, 100, 100, 100, 100 ,100, 100]
#set rows 90-119 of 'humanized_detectability' to Quillbot list
df_copyleaks.loc[90:119, 'humanized_detectability'] = Quillbot

In [16]:
#UndetectableAI
UndetectableAI = [0, 0, 0, 0, 0, 0, 0, 0 ,0, 0, 0, 100, 100, 0, 0, 100, 0, 100, 0, 100, 100, 0, 0, 100, 100 ,100, 100, 100, 0, 100]
#set rows 120-149 of 'humanized_detectability' to UndetectableAI list
df_copyleaks.loc[120:149, 'humanized_detectability'] = UndetectableAI

In [17]:
#writehuman.ai
writehumanai = [0, 0, 62, 100, 0, 0, 0, 0, 0, 0, 0, 24.4, 0, 0, 0, 0, 0, 66.6, 0, 0, 78.8, 0, 0, 0, 0, 100, 0, 0, 100, 100]
#set rows 150-179 of 'humanized_detectability' to writehumanai list
df_copyleaks.loc[150:179, 'humanized_detectability'] = writehumanai
# set rows 176 of 'humanized_detectability' to NA
df_copyleaks.loc[176, 'humanized_detectability'] = None

# Zerogpt
- use fakePercentage

In [29]:
zerogpt = pd.read_csv("zerogpt_results.csv")
print(zerogpt.shape)
zerogpt.head()

(210, 7)

,filepath,filename,fakePercentage,isHuman,feedback,aiWords,textWords
0,../datasets/essays/TOPIC3_2_GPT4.0.txt,TOPIC3_2_GPT4.0.txt,100.0,0.0,Your Text is AI/GPT Generated,593,593
1,../datasets/essays/TOPIC4_2_GPT4.0.txt,TOPIC4_2_GPT4.0.txt,100.0,0.0,Your Text is AI/GPT Generated,450,450
2,../datasets/essays/TOPIC1_1_GPT4.0.txt,TOPIC1_1_GPT4.0.txt,100.0,0.0,Your Text is AI/GPT Generated,258,258
3,../datasets/essays/TOPIC5_3_GEMINI2.5PRO.txt,TOPIC5_3_GEMINI2.5PRO.txt,100.0,0.0,Your Text is AI/GPT Generated,882,882
4,../datasets/essays/TOPIC2_1_GEMINI2.5PRO.txt,TOPIC2_1_GEMINI2.5PRO.txt,100.0,0.0,Your Text is AI/GPT Generated,276,276

In [30]:
zerogpt['type'] = None
zerogpt['topic'] = None
zerogpt['length'] = None
zerogpt['AI_model'] = None
for i, row in zerogpt.iterrows():
    type = row['filepath'].split('/')
    if len(type) == 4:
        zerogpt.at[i, 'type'] = 'AI'
    else:
        zerogpt.at[i, 'type'] = type[3]
    topic, length, model = row['filename'].split('_')
    topic = int(topic[5])
    length = int(length)
    model = model[:-4].lower()
    zerogpt.at[i, 'topic'] = topic
    zerogpt.at[i, 'length'] = length
    zerogpt.at[i, 'AI_model'] = model
zerogpt.sort_values(by=['type','topic','length', 'AI_model'], inplace=True, ignore_index=True)
zerogpt.head()

,filepath,filename,fakePercentage,isHuman,feedback,aiWords,textWords,type,topic,length,AI_model
0,../datasets/essays/TOPIC1_1_GEMINI2.5PRO.txt,TOPIC1_1_GEMINI2.5PRO.txt,100.00,0.0,Your Text is AI/GPT Generated,266,266,AI,1,1,gemini2.5pro
1,../datasets/essays/TOPIC1_1_GPT4.0.txt,TOPIC1_1_GPT4.0.txt,100.00,0.0,Your Text is AI/GPT Generated,258,258,AI,1,1,gpt4.0
2,../datasets/essays/TOPIC1_2_GEMINI2.5PRO.txt,TOPIC1_2_GEMINI2.5PRO.txt,79.21,12.5,Most of Your Text is AI/GPT Generated,476,578,AI,1,2,gemini2.5pro
3,../datasets/essays/TOPIC1_2_GPT4.0.txt,TOPIC1_2_GPT4.0.txt,100.00,0.0,Your Text is AI/GPT Generated,517,517,AI,1,2,gpt4.0
4,../datasets/essays/TOPIC1_3_GEMINI2.5PRO.txt,TOPIC1_3_GEMINI2.5PRO.txt,72.07,12.5,Most of Your Text is AI/GPT Generated,763,988,AI,1,3,gemini2.5pro

In [37]:
detect_score = zerogpt['fakePercentage'].tolist()
ai_score = detect_score[:30]
ai_score = ai_score*6
len(ai_score)

180

In [38]:
humanized_score = detect_score[30:]
len(humanized_score)

180

In [ ]:
df_zerogpt = df.copy()
df_zerogpt.sort_values(by=['humanizer','topic','length'], inplace=True, ignore_index=True)
df_zerogpt['AI_detectability'] = ai_score
df_zerogpt['humanized_detectability'] = humanized_score
df_zerogpt.head()

,topic,length,AI_model,humanizer,AI_essay,humanized_essay,AI_detectability,humanized_detectability
0,1,1,gemini2.5pro,AIHumanizer,The integration of social media into the lives...,The way social media has woven itself into the...,100.00,100.00
1,1,1,gpt4.0,AIHumanizer,Social media has undeniably transformed the wa...,Social media has really changed how young peop...,100.00,100.00
2,1,2,gemini2.5pro,AIHumanizer,The pervasive integration of social media into...,The way social media has woven itself into the...,79.21,100.00
3,1,2,gpt4.0,AIHumanizer,"In the digital age, social media has become an...","In today’s digital world, social media has rea...",100.00,100.00
4,1,3,gemini2.5pro,AIHumanizer,The integration of social media into the daily...,Social media has become such a regular part of...,72.07,92.24

# Sapling
- use 'score' column

In [46]:
sapling = pd.read_csv('sapling_results.csv')
print(sapling.shape)
sapling.head()

(210, 6)

,filepath,filename,score,sentence_score,token_probs,token
0,/Users/elizalesmana/Documents/GitHub/FYP/api/....,TOPIC3_2_GPT4.0.txt,0.999960,"[{""score"": 0.9931961718574452, ""sentence"": ""J....","[0.9999520873934671, 0.9999339143323596, 0.999...","[""J"", ""."", ""K"", ""."", "" Rowling"", ""\u2019"", ""s""..."
1,/Users/elizalesmana/Documents/GitHub/FYP/api/....,TOPIC4_2_GPT4.0.txt,0.996421,"[{""score"": 0.04109587792356928, ""sentence"": ""A...","[0.9999875543207963, 0.9999881878793531, 0.999...","[""As"", "" artificial"", "" intelligence"", "" ("", ""..."
2,/Users/elizalesmana/Documents/GitHub/FYP/api/....,TOPIC1_1_GPT4.0.txt,0.999856,"[{""score"": 0.9970659579067691, ""sentence"": ""So...","[0.9999877169693718, 0.9999878612616158, 0.999...","[""Social"", "" media"", "" has"", "" undeniably"", "" ..."
3,/Users/elizalesmana/Documents/GitHub/FYP/api/....,TOPIC5_3_GEMINI2.5PRO.txt,0.999942,"[{""score"": 3.702376560887899e-08, ""sentence"": ...","[0.9999844959274924, 0.9999861980550122, 0.999...","[""The"", "" landscape"", "" of"", "" childhood"", "" i..."
4,/Users/elizalesmana/Documents/GitHub/FYP/api/....,TOPIC2_1_GEMINI2.5PRO.txt,0.999974,"[{""score"": 0.00016756883622148777, ""sentence"":...","[0.9999881489402469, 0.9999884189392105, 0.999...","[""A"", "" silent"", "","", "" stationary"", "" fan"", ""..."

In [47]:
humanizers = ['AIHumanizer', 'Grammarly', 'HumanizeAI', 'Quillbot', 'UndetectableAI', 'writehuman.ai']
sapling['type'] = None
sapling['topic'] = None
sapling['length'] = None
sapling['AI_model'] = None
for i, row in sapling.iterrows():
    type = row['filepath'].split('/')
    isai = True
    for humanizer in humanizers:
        if humanizer in type:
            sapling.at[i, 'type'] = humanizer
            isai = False
            break
    if isai:
        sapling.at[i, 'type'] = 'AI'
    topic, length, model = row['filename'].split('_')
    topic = int(topic[5])
    length = int(length)
    model = model[:-4].lower()
    sapling.at[i, 'topic'] = topic
    sapling.at[i, 'length'] = length
    sapling.at[i, 'AI_model'] = model
sapling.sort_values(by=['type','topic','length', 'AI_model'], inplace=True, ignore_index=True)
sapling.head()

,filepath,filename,score,sentence_score,token_probs,token,type,topic,length,AI_model
0,/Users/elizalesmana/Documents/GitHub/FYP/api/....,TOPIC1_1_GEMINI2.5PRO.txt,0.999977,"[{""score"": 0.1356348630967481, ""sentence"": ""Th...","[0.9999855877567825, 0.9999863500279389, 0.999...","[""The"", "" integration"", "" of"", "" social"", "" me...",AI,1,1,gemini2.5pro
1,/Users/elizalesmana/Documents/GitHub/FYP/api/....,TOPIC1_1_GPT4.0.txt,0.999856,"[{""score"": 0.9970659579067691, ""sentence"": ""So...","[0.9999877169693718, 0.9999878612616158, 0.999...","[""Social"", "" media"", "" has"", "" undeniably"", "" ...",AI,1,1,gpt4.0
2,/Users/elizalesmana/Documents/GitHub/FYP/api/....,TOPIC1_2_GEMINI2.5PRO.txt,0.999803,"[{""score"": 0.9912204637289971, ""sentence"": ""Th...","[0.9999881291587371, 0.9999884908911554, 0.999...","[""The"", "" pervasive"", "" integration"", "" of"", ""...",AI,1,2,gemini2.5pro
3,/Users/elizalesmana/Documents/GitHub/FYP/api/....,TOPIC1_2_GPT4.0.txt,0.999874,"[{""score"": 0.9995484959432652, ""sentence"": ""In...","[0.9999889039127083, 0.999989114168784, 0.9999...","[""In"", "" the"", "" digital"", "" age"", "","", "" soci...",AI,1,2,gpt4.0
4,/Users/elizalesmana/Documents/GitHub/FYP/api/....,TOPIC1_3_GEMINI2.5PRO.txt,0.795353,"[{""score"": 0.9955431358518562, ""sentence"": ""Th...","[0.9999795212552272, 0.9999799321012688, 0.999...","[""The"", "" integration"", "" of"", "" social"", "" me...",AI,1,3,gemini2.5pro

In [48]:
detect_score = sapling['score'].tolist()
ai_score = detect_score[:30]
ai_score = ai_score*6
len(ai_score)

180

In [49]:
humanized_score = detect_score[30:]

In [50]:
df_sapling = df.copy()
df_sapling.sort_values(by=['humanizer','topic','length'], inplace=True, ignore_index=True)
df_sapling['AI_detectability'] = ai_score
df_sapling['humanized_detectability'] = humanized_score
df_sapling.head()

,topic,length,AI_model,humanizer,AI_essay,humanized_essay,AI_detectability,humanized_detectability
0,1,1,gemini2.5pro,AIHumanizer,The integration of social media into the lives...,The way social media has woven itself into the...,0.999977,0.999954
1,1,1,gpt4.0,AIHumanizer,Social media has undeniably transformed the wa...,Social media has really changed how young peop...,0.999856,0.999615
2,1,2,gemini2.5pro,AIHumanizer,The pervasive integration of social media into...,The way social media has woven itself into the...,0.999803,0.985319
3,1,2,gpt4.0,AIHumanizer,"In the digital age, social media has become an...","In today’s digital world, social media has rea...",0.999874,0.999957
4,1,3,gemini2.5pro,AIHumanizer,The integration of social media into the daily...,Social media has become such a regular part of...,0.795353,0.999904

# Combine all three dataframes

In [56]:
df_merged = df_copyleaks.merge(df_zerogpt, on=['humanizer', 'topic', 'length', 'AI_model', 'AI_essay', 'humanized_essay'], suffixes=('_copyleaks', '_zerogpt'))
df_merged = df_merged.merge(df_sapling, on=['humanizer', 'topic', 'length', 'AI_model', 'AI_essay', 'humanized_essay'])
df_merged.rename(columns={'AI_detectability': 'sapling_AI', 'humanized_detectability': 'sapling_humanized', 'AI_detectability_copyleaks': 'copyleaks_AI', 'humanized_detectability_copyleaks': 'copyleaks_humanized', 'AI_detectability_zerogpt': 'zerogpt_AI', 'humanized_detectability_zerogpt': 'zerogpt_humanized'}, inplace=True)
df_merged.head()

,topic,length,AI_model,humanizer,AI_essay,humanized_essay,copyleaks_AI,copyleaks_humanized,zerogpt_AI,zerogpt_humanized,sapling_AI,sapling_humanized
0,1,1,gemini2.5pro,AIHumanizer,The integration of social media into the lives...,The way social media has woven itself into the...,100,100.0,100.00,100.0,0.999977,0.999954
1,1,1,gpt4.0,AIHumanizer,Social media has undeniably transformed the wa...,Social media has really changed how young peop...,100,100.0,100.00,100.0,0.999856,0.999615
2,1,2,gemini2.5pro,AIHumanizer,The pervasive integration of social media into...,The way social media has woven itself into the...,100,100.0,79.21,100.0,0.999803,0.985319
3,1,2,gpt4.0,AIHumanizer,"In the digital age, social media has become an...","In today’s digital world, social media has rea...",100,100.0,100.00,100.0,0.999874,0.999957
4,1,3,gpt4.0,AIHumanizer,"In recent years, social media has revolutioniz...","Over the past few years, social media has comp...",100,100.0,99.99,100.0,0.999904,0.999358